### ISSUE TITLE
Implement modules for components

### ISSUE THREAD

**Issue by FlxB2** [PlanQK/qc-atlas-ui#22]
Many components only use the main module. This is bad practice and should be changed soon. The documentation for modules can be found [here](https://angular.io/guide/architecture-modules).

**Comment by c-mueller** [comment]
Is this still an issue? Since modules have been used for most of the components the issue resolved itself, kind of.

**Comment by FlxB2** [comment]
> Is this still an issue? Since modules have been used for most of the components the issue resolved itself, kind of.

yeah seems fine
